INSERT INTO CHAT (POSTTIME,FROMUSER,ISSINGLECAST,TOUSER,ISFILE,MESSAGE) VALUES (datetime(1092941466, 'unixepoch', 'localtime'),3,1,1,0,'nihaome');
INSERT INTO USER (ID,NAME,ISSINGLE,ISONLINE) VALUES (1,'WENCHIH',1,0);
INSERT INTO USER (ID,NAME,ISSINGLE,ISONLINE) VALUES (2,'JOHN',1,0);
INSERT INTO USER (ID,NAME,ISSINGLE,ISONLINE) VALUES (3,'BOB',1,0);
INSERT INTO RELATION (FIRSTID,SECONDID) VALUES (1,3);
