PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DROP TABLE CHAT;
CREATE TABLE CHAT(SERIALNUM INTEGER PRIMARY KEY   AUTOINCREMENT,POSTTIME INTEGER NOT NULL,FROMUSER INTEGER NOT NULL,ISSINGLECAST INTEGER NOT NULL,TOUSER INTEGER NOT NULL,ISFILE INTEGER NOT NULL,MESSAGE TEXT NOT NULL);
COMMIT;
